package br.eti.rslemos.specialist.pt_BR;

import br.eti.rslemos.tagger.DefaultTag;
import br.eti.rslemos.tagger.MatcherListTokenTagger;
import br.eti.rslemos.tagger.Tagger;
import br.eti.rslemos.tagger.MatcherListTokenTagger.StringMatcher;
import br.eti.rslemos.tagger.MatcherListTokenTagger.SuffixMatcher;

public class VerbTaggerByInflection {
	public static final Tagger REGULAR_VERB = new MatcherListTokenTagger(
		// verbos regulares
		new SuffixMatcher("ando", new DefaultTag("v-ger")),
		new SuffixMatcher("endo", new DefaultTag("v-ger")),
		new SuffixMatcher("indo", new DefaultTag("v-ger")),
	
		new SuffixMatcher("ado", new DefaultTag("v-pcp")),
		new SuffixMatcher("ido", new DefaultTag("v-pcp")),
	
		new SuffixMatcher("íssemos", new DefaultTag("v-fin")),
		new SuffixMatcher("iríamos", new DefaultTag("v-fin")),
		new SuffixMatcher("êssemos", new DefaultTag("v-fin")),
		new SuffixMatcher("eríamos", new DefaultTag("v-fin")),
		new SuffixMatcher("ássemos", new DefaultTag("v-fin")),
		new SuffixMatcher("aríamos", new DefaultTag("v-fin")),
		new SuffixMatcher("ísseis", new DefaultTag("v-fin")),
		new SuffixMatcher("iríeis", new DefaultTag("v-fin")),
		new SuffixMatcher("iremos", new DefaultTag("v-fin")),
		new SuffixMatcher("íramos", new DefaultTag("v-fin")),
		new SuffixMatcher("êsseis", new DefaultTag("v-fin")),
		new SuffixMatcher("eríeis", new DefaultTag("v-fin")),
		new SuffixMatcher("eremos", new DefaultTag("v-fin")),
		new SuffixMatcher("êramos", new DefaultTag("v-fin")),
		new SuffixMatcher("ávamos", new DefaultTag("v-fin")),
		new SuffixMatcher("ásseis", new DefaultTag("v-fin")),
		new SuffixMatcher("aríeis", new DefaultTag("v-fin")),
		new SuffixMatcher("aremos", new DefaultTag("v-fin")),
		new SuffixMatcher("áramos", new DefaultTag("v-fin")),
		new SuffixMatcher("istes", new DefaultTag("v-fin")),
		new SuffixMatcher("isses", new DefaultTag("v-fin")),
		new SuffixMatcher("issem", new DefaultTag("v-fin")),
		new SuffixMatcher("irmos", new DefaultTag("v-fin")),
		new SuffixMatcher("irias", new DefaultTag("v-fin")),
		new SuffixMatcher("iriam", new DefaultTag("v-fin")),
		new SuffixMatcher("íreis", new DefaultTag("v-fin")),
		new SuffixMatcher("ireis", new DefaultTag("v-fin")),
		new SuffixMatcher("irdes", new DefaultTag("v-fin")),
		new SuffixMatcher("íamos", new DefaultTag("v-fin")),
		new SuffixMatcher("estes", new DefaultTag("v-fin")),
		new SuffixMatcher("esses", new DefaultTag("v-fin")),
		new SuffixMatcher("essem", new DefaultTag("v-fin")),
		new SuffixMatcher("ermos", new DefaultTag("v-fin")),
		new SuffixMatcher("erias", new DefaultTag("v-fin")),
		new SuffixMatcher("eriam", new DefaultTag("v-fin")),
		new SuffixMatcher("êreis", new DefaultTag("v-fin")),
		new SuffixMatcher("ereis", new DefaultTag("v-fin")),
		new SuffixMatcher("erdes", new DefaultTag("v-fin")),
		new SuffixMatcher("áveis", new DefaultTag("v-fin")),
		new SuffixMatcher("astes", new DefaultTag("v-fin")),
		new SuffixMatcher("asses", new DefaultTag("v-fin")),
		new SuffixMatcher("assem", new DefaultTag("v-fin")),
		new SuffixMatcher("armos", new DefaultTag("v-fin")),
		new SuffixMatcher("arias", new DefaultTag("v-fin")),
		new SuffixMatcher("ariam", new DefaultTag("v-fin")),
		new SuffixMatcher("áreis", new DefaultTag("v-fin")),
		new SuffixMatcher("areis", new DefaultTag("v-fin")),
		new SuffixMatcher("ardes", new DefaultTag("v-fin")),
		new SuffixMatcher("iste", new DefaultTag("v-fin")),
		new SuffixMatcher("isse", new DefaultTag("v-fin")),
		new SuffixMatcher("iria", new DefaultTag("v-fin")),
		new SuffixMatcher("ires", new DefaultTag("v-fin")),
		new SuffixMatcher("irem", new DefaultTag("v-fin")),
		new SuffixMatcher("irei", new DefaultTag("v-fin")),
		new SuffixMatcher("iras", new DefaultTag("v-fin")),
		new SuffixMatcher("irás", new DefaultTag("v-fin")),
		new SuffixMatcher("irão", new DefaultTag("v-fin")),
		new SuffixMatcher("iram", new DefaultTag("v-fin")),
		new SuffixMatcher("imos", new DefaultTag("v-fin")),
		new SuffixMatcher("íeis", new DefaultTag("v-fin")),
		new SuffixMatcher("este", new DefaultTag("v-fin")),
		new SuffixMatcher("esse", new DefaultTag("v-fin")),
		new SuffixMatcher("eria", new DefaultTag("v-fin")),
		new SuffixMatcher("eres", new DefaultTag("v-fin")),
		new SuffixMatcher("erem", new DefaultTag("v-fin")),
		new SuffixMatcher("erei", new DefaultTag("v-fin")),
		new SuffixMatcher("eras", new DefaultTag("v-fin")),
		new SuffixMatcher("erás", new DefaultTag("v-fin")),
		new SuffixMatcher("erão", new DefaultTag("v-fin")),
		new SuffixMatcher("eram", new DefaultTag("v-fin")),
		new SuffixMatcher("emos", new DefaultTag("v-fin")),
		new SuffixMatcher("avas", new DefaultTag("v-fin")),
		new SuffixMatcher("avam", new DefaultTag("v-fin")),
		new SuffixMatcher("aste", new DefaultTag("v-fin")),
		new SuffixMatcher("asse", new DefaultTag("v-fin")),
		new SuffixMatcher("aria", new DefaultTag("v-fin")),
		new SuffixMatcher("ares", new DefaultTag("v-fin")),
		new SuffixMatcher("arem", new DefaultTag("v-fin")),
		new SuffixMatcher("arei", new DefaultTag("v-fin")),
		new SuffixMatcher("aras", new DefaultTag("v-fin")),
		new SuffixMatcher("arás", new DefaultTag("v-fin")),
		new SuffixMatcher("arão", new DefaultTag("v-fin")),
		new SuffixMatcher("aram", new DefaultTag("v-fin")),
		new SuffixMatcher("amos", new DefaultTag("v-fin")),
		new SuffixMatcher("ira", new DefaultTag("v-fin")),
		new SuffixMatcher("irá", new DefaultTag("v-fin")),
		new SuffixMatcher("ias", new DefaultTag("v-fin")),
		new SuffixMatcher("iam", new DefaultTag("v-fin")),
		new SuffixMatcher("era", new DefaultTag("v-fin")),
		new SuffixMatcher("erá", new DefaultTag("v-fin")),
		new SuffixMatcher("eis", new DefaultTag("v-fin")),
		new SuffixMatcher("ava", new DefaultTag("v-fin")),
		new SuffixMatcher("ara", new DefaultTag("v-fin")),
		new SuffixMatcher("ará", new DefaultTag("v-fin")),
		new SuffixMatcher("ais", new DefaultTag("v-fin")),
		new SuffixMatcher("ou", new DefaultTag("v-fin")),
		new SuffixMatcher("iu", new DefaultTag("v-fin")),
		new SuffixMatcher("is", new DefaultTag("v-fin")),
//		new SuffixMatcher("ir", new DefaultTag("v-fin")),
		new SuffixMatcher("ia", new DefaultTag("v-fin")),
		new SuffixMatcher("eu", new DefaultTag("v-fin")),
		new SuffixMatcher("es", new DefaultTag("v-fin")),
//		new SuffixMatcher("er", new DefaultTag("v-fin")),
		new SuffixMatcher("em", new DefaultTag("v-fin")),
		new SuffixMatcher("ei", new DefaultTag("v-fin")),
		new SuffixMatcher("as", new DefaultTag("v-fin")),
//		new SuffixMatcher("ar", new DefaultTag("v-fin")),
		new SuffixMatcher("am", new DefaultTag("v-fin")),
		new SuffixMatcher("ai", new DefaultTag("v-fin")),
//		new SuffixMatcher("o", new DefaultTag("v-fin")),
//		new SuffixMatcher("i", new DefaultTag("v-fin")),
//		new SuffixMatcher("e", new DefaultTag("v-fin")),
//		new SuffixMatcher("a", new DefaultTag("v-fin")),
	
		new SuffixMatcher("ar", new DefaultTag("v-inf")),
		new SuffixMatcher("er", new DefaultTag("v-inf")),
		new SuffixMatcher("ir", new DefaultTag("v-inf"))
	
	);
	
	public static final Tagger VERB_SER = new MatcherListTokenTagger(
			new StringMatcher("sendo", new DefaultTag("v-ger")),
			new StringMatcher("sido", new DefaultTag("v-pcp")),

			new StringMatcher("sou", new DefaultTag("v-fin")),
			new StringMatcher("és", new DefaultTag("v-fin")),
			new StringMatcher("é", new DefaultTag("v-fin")),
			new StringMatcher("somos", new DefaultTag("v-fin")),
			new StringMatcher("sois", new DefaultTag("v-fin")),
			new StringMatcher("são", new DefaultTag("v-fin")),
			new StringMatcher("fui", new DefaultTag("v-fin")),
			new StringMatcher("foste", new DefaultTag("v-fin")),
			new StringMatcher("foi", new DefaultTag("v-fin")),
			new StringMatcher("fomos", new DefaultTag("v-fin")),
			new StringMatcher("fostes", new DefaultTag("v-fin")),
			new StringMatcher("foram", new DefaultTag("v-fin")),
			new StringMatcher("era", new DefaultTag("v-fin")),
			new StringMatcher("eras", new DefaultTag("v-fin")),
			new StringMatcher("era", new DefaultTag("v-fin")),
			new StringMatcher("éramos", new DefaultTag("v-fin")),
			new StringMatcher("éreis", new DefaultTag("v-fin")),
			new StringMatcher("eram", new DefaultTag("v-fin")),
			new StringMatcher("fora", new DefaultTag("v-fin")),
			new StringMatcher("foras", new DefaultTag("v-fin")),
			new StringMatcher("fora", new DefaultTag("v-fin")),
			new StringMatcher("fôramos", new DefaultTag("v-fin")),
			new StringMatcher("fôreis", new DefaultTag("v-fin")),
			new StringMatcher("foram", new DefaultTag("v-fin")),
			new StringMatcher("serei", new DefaultTag("v-fin")),
			new StringMatcher("sereis", new DefaultTag("v-fin")),
			new StringMatcher("será", new DefaultTag("v-fin")),
			new StringMatcher("seremos", new DefaultTag("v-fin")),
			new StringMatcher("sereis", new DefaultTag("v-fin")),
			new StringMatcher("serão", new DefaultTag("v-fin")),
			new StringMatcher("seria", new DefaultTag("v-fin")),
			new StringMatcher("serias", new DefaultTag("v-fin")),
			new StringMatcher("seria", new DefaultTag("v-fin")),
			new StringMatcher("seríamos", new DefaultTag("v-fin")),
			new StringMatcher("seríeis", new DefaultTag("v-fin")),
			new StringMatcher("seriam", new DefaultTag("v-fin")),
			new StringMatcher("seja", new DefaultTag("v-fin")),
			new StringMatcher("sejas", new DefaultTag("v-fin")),
			new StringMatcher("seja", new DefaultTag("v-fin")),
			new StringMatcher("sejamos", new DefaultTag("v-fin")),
			new StringMatcher("sejais", new DefaultTag("v-fin")),
			new StringMatcher("sejam", new DefaultTag("v-fin")),
			new StringMatcher("fosse", new DefaultTag("v-fin")),
			new StringMatcher("fosses", new DefaultTag("v-fin")),
			new StringMatcher("fosse", new DefaultTag("v-fin")),
			new StringMatcher("fôssemos", new DefaultTag("v-fin")),
			new StringMatcher("fôsseis", new DefaultTag("v-fin")),
			new StringMatcher("fossem", new DefaultTag("v-fin")),
			new StringMatcher("for", new DefaultTag("v-fin")),
			new StringMatcher("fores", new DefaultTag("v-fin")),
			new StringMatcher("for", new DefaultTag("v-fin")),
			new StringMatcher("formos", new DefaultTag("v-fin")),
			new StringMatcher("fordes", new DefaultTag("v-fin")),
			new StringMatcher("forem", new DefaultTag("v-fin")),
			new StringMatcher("sê", new DefaultTag("v-fin")),
			new StringMatcher("seja", new DefaultTag("v-fin")),
			new StringMatcher("sejamos", new DefaultTag("v-fin")),
			new StringMatcher("sede", new DefaultTag("v-fin")),
			new StringMatcher("sejam", new DefaultTag("v-fin")),
			new StringMatcher("sejas", new DefaultTag("v-fin")),
			new StringMatcher("seja", new DefaultTag("v-fin")),
			new StringMatcher("sejamos", new DefaultTag("v-fin")),
			new StringMatcher("sejais", new DefaultTag("v-fin")),
			new StringMatcher("sejam", new DefaultTag("v-fin")),

			new StringMatcher("ser", new DefaultTag("v-inf")),
			new StringMatcher("seres", new DefaultTag("v-inf")),
			new StringMatcher("ser", new DefaultTag("v-inf")),
			new StringMatcher("sermos", new DefaultTag("v-inf")),
			new StringMatcher("serdes", new DefaultTag("v-inf")),
			new StringMatcher("serem", new DefaultTag("v-inf"))
		);
	public static final Tagger VERB_ESTAR = new MatcherListTokenTagger(
			new StringMatcher("estando", new DefaultTag("v-ger")),

			new StringMatcher("estado", new DefaultTag("v-pcp")),
			new StringMatcher("estada", new DefaultTag("v-pcp")),
			new StringMatcher("estados", new DefaultTag("v-pcp")),
			new StringMatcher("estadas", new DefaultTag("v-pcp"))

			
		);
}
