package br.eti.rslemos.specialist.pt_BR;

import br.eti.rslemos.tagger.MatcherListTokenTagger;
import br.eti.rslemos.tagger.Tagger;
import br.eti.rslemos.tagger.MatcherListTokenTagger.StringMatcher;
import br.eti.rslemos.tagger.MatcherListTokenTagger.SuffixMatcher;

public class VerbTaggerByInflection {
	public static final Tagger<String> REGULAR_VERB = new MatcherListTokenTagger<String>(
		// verbos regulares
		new SuffixMatcher<String>("ando", "v-ger"),
		new SuffixMatcher<String>("endo", "v-ger"),
		new SuffixMatcher<String>("indo", "v-ger"),
	
		new SuffixMatcher<String>("ado", "v-pcp"),
		new SuffixMatcher<String>("ido", "v-pcp"),
	
		new SuffixMatcher<String>("íssemos", "v-fin"),
		new SuffixMatcher<String>("iríamos", "v-fin"),
		new SuffixMatcher<String>("êssemos", "v-fin"),
		new SuffixMatcher<String>("eríamos", "v-fin"),
		new SuffixMatcher<String>("ássemos", "v-fin"),
		new SuffixMatcher<String>("aríamos", "v-fin"),
		new SuffixMatcher<String>("ísseis", "v-fin"),
		new SuffixMatcher<String>("iríeis", "v-fin"),
		new SuffixMatcher<String>("iremos", "v-fin"),
		new SuffixMatcher<String>("íramos", "v-fin"),
		new SuffixMatcher<String>("êsseis", "v-fin"),
		new SuffixMatcher<String>("eríeis", "v-fin"),
		new SuffixMatcher<String>("eremos", "v-fin"),
		new SuffixMatcher<String>("êramos", "v-fin"),
		new SuffixMatcher<String>("ávamos", "v-fin"),
		new SuffixMatcher<String>("ásseis", "v-fin"),
		new SuffixMatcher<String>("aríeis", "v-fin"),
		new SuffixMatcher<String>("aremos", "v-fin"),
		new SuffixMatcher<String>("áramos", "v-fin"),
		new SuffixMatcher<String>("istes", "v-fin"),
		new SuffixMatcher<String>("isses", "v-fin"),
		new SuffixMatcher<String>("issem", "v-fin"),
		new SuffixMatcher<String>("irmos", "v-fin"),
		new SuffixMatcher<String>("irias", "v-fin"),
		new SuffixMatcher<String>("iriam", "v-fin"),
		new SuffixMatcher<String>("íreis", "v-fin"),
		new SuffixMatcher<String>("ireis", "v-fin"),
		new SuffixMatcher<String>("irdes", "v-fin"),
		new SuffixMatcher<String>("íamos", "v-fin"),
		new SuffixMatcher<String>("estes", "v-fin"),
		new SuffixMatcher<String>("esses", "v-fin"),
		new SuffixMatcher<String>("essem", "v-fin"),
		new SuffixMatcher<String>("ermos", "v-fin"),
		new SuffixMatcher<String>("erias", "v-fin"),
		new SuffixMatcher<String>("eriam", "v-fin"),
		new SuffixMatcher<String>("êreis", "v-fin"),
		new SuffixMatcher<String>("ereis", "v-fin"),
		new SuffixMatcher<String>("erdes", "v-fin"),
		new SuffixMatcher<String>("áveis", "v-fin"),
		new SuffixMatcher<String>("astes", "v-fin"),
		new SuffixMatcher<String>("asses", "v-fin"),
		new SuffixMatcher<String>("assem", "v-fin"),
		new SuffixMatcher<String>("armos", "v-fin"),
		new SuffixMatcher<String>("arias", "v-fin"),
		new SuffixMatcher<String>("ariam", "v-fin"),
		new SuffixMatcher<String>("áreis", "v-fin"),
		new SuffixMatcher<String>("areis", "v-fin"),
		new SuffixMatcher<String>("ardes", "v-fin"),
		new SuffixMatcher<String>("iste", "v-fin"),
		new SuffixMatcher<String>("isse", "v-fin"),
		new SuffixMatcher<String>("iria", "v-fin"),
		new SuffixMatcher<String>("ires", "v-fin"),
		new SuffixMatcher<String>("irem", "v-fin"),
		new SuffixMatcher<String>("irei", "v-fin"),
		new SuffixMatcher<String>("iras", "v-fin"),
		new SuffixMatcher<String>("irás", "v-fin"),
		new SuffixMatcher<String>("irão", "v-fin"),
		new SuffixMatcher<String>("iram", "v-fin"),
		new SuffixMatcher<String>("imos", "v-fin"),
		new SuffixMatcher<String>("íeis", "v-fin"),
		new SuffixMatcher<String>("este", "v-fin"),
		new SuffixMatcher<String>("esse", "v-fin"),
		new SuffixMatcher<String>("eria", "v-fin"),
		new SuffixMatcher<String>("eres", "v-fin"),
		new SuffixMatcher<String>("erem", "v-fin"),
		new SuffixMatcher<String>("erei", "v-fin"),
		new SuffixMatcher<String>("eras", "v-fin"),
		new SuffixMatcher<String>("erás", "v-fin"),
		new SuffixMatcher<String>("erão", "v-fin"),
		new SuffixMatcher<String>("eram", "v-fin"),
		new SuffixMatcher<String>("emos", "v-fin"),
		new SuffixMatcher<String>("avas", "v-fin"),
		new SuffixMatcher<String>("avam", "v-fin"),
		new SuffixMatcher<String>("aste", "v-fin"),
		new SuffixMatcher<String>("asse", "v-fin"),
		new SuffixMatcher<String>("aria", "v-fin"),
		new SuffixMatcher<String>("ares", "v-fin"),
		new SuffixMatcher<String>("arem", "v-fin"),
		new SuffixMatcher<String>("arei", "v-fin"),
		new SuffixMatcher<String>("aras", "v-fin"),
		new SuffixMatcher<String>("arás", "v-fin"),
		new SuffixMatcher<String>("arão", "v-fin"),
		new SuffixMatcher<String>("aram", "v-fin"),
		new SuffixMatcher<String>("amos", "v-fin"),
		new SuffixMatcher<String>("ira", "v-fin"),
		new SuffixMatcher<String>("irá", "v-fin"),
		new SuffixMatcher<String>("ias", "v-fin"),
		new SuffixMatcher<String>("iam", "v-fin"),
		new SuffixMatcher<String>("era", "v-fin"),
		new SuffixMatcher<String>("erá", "v-fin"),
		new SuffixMatcher<String>("eis", "v-fin"),
		new SuffixMatcher<String>("ava", "v-fin"),
		new SuffixMatcher<String>("ara", "v-fin"),
		new SuffixMatcher<String>("ará", "v-fin"),
		new SuffixMatcher<String>("ais", "v-fin"),
		new SuffixMatcher<String>("ou", "v-fin"),
		new SuffixMatcher<String>("iu", "v-fin"),
		new SuffixMatcher<String>("is", "v-fin"),
//		new SuffixMatcher<String>("ir", "v-fin"),
		new SuffixMatcher<String>("ia", "v-fin"),
		new SuffixMatcher<String>("eu", "v-fin"),
		new SuffixMatcher<String>("es", "v-fin"),
//		new SuffixMatcher<String>("er", "v-fin"),
		new SuffixMatcher<String>("em", "v-fin"),
		new SuffixMatcher<String>("ei", "v-fin"),
		new SuffixMatcher<String>("as", "v-fin"),
//		new SuffixMatcher<String>("ar", "v-fin"),
		new SuffixMatcher<String>("am", "v-fin"),
		new SuffixMatcher<String>("ai", "v-fin"),
//		new SuffixMatcher<String>("o", "v-fin"),
//		new SuffixMatcher<String>("i", "v-fin"),
//		new SuffixMatcher<String>("e", "v-fin"),
//		new SuffixMatcher<String>("a", "v-fin"),
	
		new SuffixMatcher<String>("ar", "v-inf"),
		new SuffixMatcher<String>("er", "v-inf"),
		new SuffixMatcher<String>("ir", "v-inf")
	
	);
	
	public static final Tagger<String> VERB_SER = new MatcherListTokenTagger<String>(
			new StringMatcher<String>("sendo", "v-ger"),
			new StringMatcher<String>("sido", "v-pcp"),

			new StringMatcher<String>("sou", "v-fin"),
			new StringMatcher<String>("és", "v-fin"),
			new StringMatcher<String>("é", "v-fin"),
			new StringMatcher<String>("somos", "v-fin"),
			new StringMatcher<String>("sois", "v-fin"),
			new StringMatcher<String>("são", "v-fin"),
			new StringMatcher<String>("fui", "v-fin"),
			new StringMatcher<String>("foste", "v-fin"),
			new StringMatcher<String>("foi", "v-fin"),
			new StringMatcher<String>("fomos", "v-fin"),
			new StringMatcher<String>("fostes", "v-fin"),
			new StringMatcher<String>("foram", "v-fin"),
			new StringMatcher<String>("era", "v-fin"),
			new StringMatcher<String>("eras", "v-fin"),
			new StringMatcher<String>("era", "v-fin"),
			new StringMatcher<String>("éramos", "v-fin"),
			new StringMatcher<String>("éreis", "v-fin"),
			new StringMatcher<String>("eram", "v-fin"),
			new StringMatcher<String>("fora", "v-fin"),
			new StringMatcher<String>("foras", "v-fin"),
			new StringMatcher<String>("fora", "v-fin"),
			new StringMatcher<String>("fôramos", "v-fin"),
			new StringMatcher<String>("fôreis", "v-fin"),
			new StringMatcher<String>("foram", "v-fin"),
			new StringMatcher<String>("serei", "v-fin"),
			new StringMatcher<String>("sereis", "v-fin"),
			new StringMatcher<String>("será", "v-fin"),
			new StringMatcher<String>("seremos", "v-fin"),
			new StringMatcher<String>("sereis", "v-fin"),
			new StringMatcher<String>("serão", "v-fin"),
			new StringMatcher<String>("seria", "v-fin"),
			new StringMatcher<String>("serias", "v-fin"),
			new StringMatcher<String>("seria", "v-fin"),
			new StringMatcher<String>("seríamos", "v-fin"),
			new StringMatcher<String>("seríeis", "v-fin"),
			new StringMatcher<String>("seriam", "v-fin"),
			new StringMatcher<String>("seja", "v-fin"),
			new StringMatcher<String>("sejas", "v-fin"),
			new StringMatcher<String>("seja", "v-fin"),
			new StringMatcher<String>("sejamos", "v-fin"),
			new StringMatcher<String>("sejais", "v-fin"),
			new StringMatcher<String>("sejam", "v-fin"),
			new StringMatcher<String>("fosse", "v-fin"),
			new StringMatcher<String>("fosses", "v-fin"),
			new StringMatcher<String>("fosse", "v-fin"),
			new StringMatcher<String>("fôssemos", "v-fin"),
			new StringMatcher<String>("fôsseis", "v-fin"),
			new StringMatcher<String>("fossem", "v-fin"),
			new StringMatcher<String>("for", "v-fin"),
			new StringMatcher<String>("fores", "v-fin"),
			new StringMatcher<String>("for", "v-fin"),
			new StringMatcher<String>("formos", "v-fin"),
			new StringMatcher<String>("fordes", "v-fin"),
			new StringMatcher<String>("forem", "v-fin"),
			new StringMatcher<String>("sê", "v-fin"),
			new StringMatcher<String>("seja", "v-fin"),
			new StringMatcher<String>("sejamos", "v-fin"),
			new StringMatcher<String>("sede", "v-fin"),
			new StringMatcher<String>("sejam", "v-fin"),
			new StringMatcher<String>("sejas", "v-fin"),
			new StringMatcher<String>("seja", "v-fin"),
			new StringMatcher<String>("sejamos", "v-fin"),
			new StringMatcher<String>("sejais", "v-fin"),
			new StringMatcher<String>("sejam", "v-fin"),

			new StringMatcher<String>("ser", "v-inf"),
			new StringMatcher<String>("seres", "v-inf"),
			new StringMatcher<String>("ser", "v-inf"),
			new StringMatcher<String>("sermos", "v-inf"),
			new StringMatcher<String>("serdes", "v-inf"),
			new StringMatcher<String>("serem", "v-inf")
		);
	public static final Tagger<String> VERB_ESTAR = new MatcherListTokenTagger<String>(
			new StringMatcher<String>("estando", "v-ger"),

			new StringMatcher<String>("estado", "v-pcp"),
			new StringMatcher<String>("estada", "v-pcp"),
			new StringMatcher<String>("estados", "v-pcp"),
			new StringMatcher<String>("estadas", "v-pcp")

			
		);
}
