package br.eti.rslemos.brill.rules;

public interface RuleSets {
	static final RuleFactory[] BRILL = {
		CURWDRule.FACTORY,
		LBIGRAMRule.FACTORY,
		NEXT1OR2OR3TAGRule.FACTORY1, NEXT1OR2OR3TAGRule.FACTORY2, NEXT1OR2OR3TAGRule.FACTORY3,
		NEXT1OR2TAGRule.FACTORY1, NEXT1OR2TAGRule.FACTORY2,
		NEXT1OR2WDRule.FACTORY1, NEXT1OR2WDRule.FACTORY2,
		NEXT2TAGRule.FACTORY,
		NEXT2WDRule.FACTORY,
		NEXTBIGRAMRule.FACTORY,
		NEXTTAGRule.FACTORY,
		NEXTWDRule.FACTORY,
		PREV1OR2OR3TAGRule.FACTORY1, PREV1OR2OR3TAGRule.FACTORY2, PREV1OR2OR3TAGRule.FACTORY3,
		PREV1OR2TAGRule.FACTORY1, PREV1OR2TAGRule.FACTORY2,
		PREV1OR2WDRule.FACTORY1, PREV1OR2WDRule.FACTORY2,
		PREV2TAGRule.FACTORY,
		PREV2WDRule.FACTORY,
		PREVBIGRAMRule.FACTORY,
		PREVTAGRule.FACTORY,
		PREVWDRule.FACTORY,
		RBIGRAMRule.FACTORY,
		SURROUNDTAGRule.FACTORY,
		WDAND2AFTRule.FACTORY,
		WDAND2BFRRule.FACTORY,
		WDAND2TAGAFTRule.FACTORY,
		WDAND2TAGBFRRule.FACTORY,
		WDNEXTTAGRule.FACTORY,
		WDPREVTAGRule.FACTORY,		
	};
}
