//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.19 at 02:54:38 PM BRT 
//


package br.eti.rslemos.tigerapi.model;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for annotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="feature" type="{}featureType" maxOccurs="unbounded"/>
 *         &lt;element name="edgelabel" type="{}edgelabelType" minOccurs="0"/>
 *         &lt;element name="secedgelabel" type="{}edgelabelType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annotationType", propOrder = {
    "feature",
    "edgelabel",
    "secedgelabel"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
public class AnnotationType {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    protected List<FeatureType> feature;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    protected EdgelabelType edgelabel;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    protected EdgelabelType secedgelabel;

    /**
     * Gets the value of the feature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public List<FeatureType> getFeature() {
        if (feature == null) {
            feature = new ArrayList<FeatureType>();
        }
        return this.feature;
    }

    /**
     * Gets the value of the edgelabel property.
     * 
     * @return
     *     possible object is
     *     {@link EdgelabelType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public EdgelabelType getEdgelabel() {
        return edgelabel;
    }

    /**
     * Sets the value of the edgelabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgelabelType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public void setEdgelabel(EdgelabelType value) {
        this.edgelabel = value;
    }

    /**
     * Gets the value of the secedgelabel property.
     * 
     * @return
     *     possible object is
     *     {@link EdgelabelType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public EdgelabelType getSecedgelabel() {
        return secedgelabel;
    }

    /**
     * Sets the value of the secedgelabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgelabelType }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public void setSecedgelabel(EdgelabelType value) {
        this.secedgelabel = value;
    }

}
