//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.19 at 02:54:38 PM BRT 
//


package br.eti.rslemos.tigerapi.model;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="subcorpus" type="{}subcorpusType"/>
 *         &lt;element name="s" type="{}sentenceType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyType", propOrder = {
    "subcorpusOrS"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
public class BodyType {

    @XmlElements({
        @XmlElement(name = "s", type = SentenceType.class),
        @XmlElement(name = "subcorpus", type = SubcorpusType.class)
    })
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    protected List<Object> subcorpusOrS;

    /**
     * Gets the value of the subcorpusOrS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subcorpusOrS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubcorpusOrS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SentenceType }
     * {@link SubcorpusType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public List<Object> getSubcorpusOrS() {
        if (subcorpusOrS == null) {
            subcorpusOrS = new ArrayList<Object>();
        }
        return this.subcorpusOrS;
    }

}
