//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.19 at 02:54:38 PM BRT 
//


package br.eti.rslemos.tigerapi.model;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="variable" type="{}varType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="subgraph" use="required" type="{}idrefType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchType", propOrder = {
    "variable"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
public class MatchType {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    protected List<VarType> variable;
    @XmlAttribute(required = true)
    @XmlIDREF
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    protected Object subgraph;

    /**
     * Gets the value of the variable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VarType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public List<VarType> getVariable() {
        if (variable == null) {
            variable = new ArrayList<VarType>();
        }
        return this.variable;
    }

    /**
     * Gets the value of the subgraph property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public Object getSubgraph() {
        return subgraph;
    }

    /**
     * Sets the value of the subgraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2009-04-19T02:54:38-03:00", comments = "JAXB RI vJAXB 2.1.3 in JDK")
    public void setSubgraph(Object value) {
        this.subgraph = value;
    }

}
